

# This workflow will deploy a DotNet project

name: DotNet CD

on: 
  push:
    branches: [ master ]
    paths:
    - 'apis/poi/**'
env:
  REGISTRY: openhackufq2qk03acr.azurecr.io
  IMAGE_NAME: devopsoh/api-poi
  APP_NAME: openhackufq2qk03poi
  PROJECT_PATH: apis/poi/web
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to ACR
        uses: docker/login-action@v1 
        with:
          registry: ${{env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{env.PROJECT_PATH }}
          file: ${{env.PROJECT_PATH }}/Dockerfile
          tags: ${{env.REGISTRY }}/${{env.IMAGE_NAME }}:${{ github.sha }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{env.APP_NAME }}
        images: ${{env.REGISTRY }}/${{env.IMAGE_NAME }}:${{ github.sha }}
