# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
    paths:
    - 'apis/user-java/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'apis/user-java/**'
  workflow_dispatch:  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      working-directory: apis/user-java
      run: mvn clean install 
    - name: Test Maven
      working-directory: apis/user-java
      run: mvn test
    - name: The job has failed 
      if: ${{failure() }}
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/ISSUE_TEMPLATE2.md
