# This workflow will build, test and deploy a NodeJS project

name: NodeJS CI, CD

on: [push]

env:
  REGISTRY: openhackufq2qk03acr.azurecr.io
  IMAGE_NAME: devopsoh/api-userprofile
  APP_NAME: openhackufq2qk03userprofile
  PROJECT_PATH: apis/userprofile
  WORK_DIR: apis/userprofile
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: az account show
